species: mouse

AS_event:
  - kmer/SE_inclusion_dn
  - kmer/SE_inclusion_up
  - kmer/SE_inclusion_all

Rscript_path: /home/xfu/R/3.2.4/bin/Rscript

genome: /home/xfu/Gmatic5/genome/mm10/mm10.fa

ASTA: /home/xfu/Gmatic5/gene/mm10_vM13/ASTA/gencode_astalavista_SE.bed

kmer: 
  - 5
  - 6

region_len: 
  - 100
  - 300
